spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    name: south #数据库名
    url: jdbc:mysql://localhost:3306/south?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=PRC #url
    username: root #用户名
    password: 123456 #密码
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动
#mybatis:
#  mapper-locations: classpath:mapper/*.xml #配置映射文件
#  type-aliases-package: com.nc.springboot_01.bean.Good #配置实体类